# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab67958373015698f4fe1df2f660e606ca4a839f90a2e9b1d2427b7caaf6a11881be700c0bad17f927d4153e7eef31b99c814597c83084a229ab1db0fe95122f

test:
  secret_key_base: 558443fe6f44ed259eab4a4842796cf264076266e7b9ef11cfa661dfa49d54d84c3d94f65d16ff31b22192035ddc369c7d8db109d3c390c50094b26663cb00c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
